// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: src/main/protobuf/bazel_flags.proto

package bazel_flags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	HasNegativeFlag       *bool                  `protobuf:"varint,2,opt,name=has_negative_flag,json=hasNegativeFlag,def=0" json:"has_negative_flag,omitempty"`
	Documentation         *string                `protobuf:"bytes,3,opt,name=documentation" json:"documentation,omitempty"`
	Commands              []string               `protobuf:"bytes,4,rep,name=commands" json:"commands,omitempty"`
	Abbreviation          *string                `protobuf:"bytes,5,opt,name=abbreviation" json:"abbreviation,omitempty"`
	AllowsMultiple        *bool                  `protobuf:"varint,6,opt,name=allows_multiple,json=allowsMultiple,def=0" json:"allows_multiple,omitempty"`
	EffectTags            []string               `protobuf:"bytes,7,rep,name=effect_tags,json=effectTags" json:"effect_tags,omitempty"`
	MetadataTags          []string               `protobuf:"bytes,8,rep,name=metadata_tags,json=metadataTags" json:"metadata_tags,omitempty"`
	DocumentationCategory *string                `protobuf:"bytes,9,opt,name=documentation_category,json=documentationCategory" json:"documentation_category,omitempty"`
	RequiresValue         *bool                  `protobuf:"varint,10,opt,name=requires_value,json=requiresValue" json:"requires_value,omitempty"`
	DefaultValue          *string                `protobuf:"bytes,13,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	OldName               *string                `protobuf:"bytes,11,opt,name=old_name,json=oldName" json:"old_name,omitempty"`
	DeprecationWarning    *string                `protobuf:"bytes,12,opt,name=deprecation_warning,json=deprecationWarning" json:"deprecation_warning,omitempty"`
	OptionExpansions      []string               `protobuf:"bytes,14,rep,name=option_expansions,json=optionExpansions" json:"option_expansions,omitempty"`
	TypeConverter         *string                `protobuf:"bytes,15,opt,name=type_converter,json=typeConverter" json:"type_converter,omitempty"`
	EnumValues            []string               `protobuf:"bytes,16,rep,name=enum_values,json=enumValues" json:"enum_values,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

// Default values for FlagInfo fields.
const (
	Default_FlagInfo_HasNegativeFlag = bool(false)
	Default_FlagInfo_AllowsMultiple  = bool(false)
)

func (x *FlagInfo) Reset() {
	*x = FlagInfo{}
	mi := &file_src_main_protobuf_bazel_flags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagInfo) ProtoMessage() {}

func (x *FlagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_bazel_flags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagInfo.ProtoReflect.Descriptor instead.
func (*FlagInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_bazel_flags_proto_rawDescGZIP(), []int{0}
}

func (x *FlagInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FlagInfo) GetHasNegativeFlag() bool {
	if x != nil && x.HasNegativeFlag != nil {
		return *x.HasNegativeFlag
	}
	return Default_FlagInfo_HasNegativeFlag
}

func (x *FlagInfo) GetDocumentation() string {
	if x != nil && x.Documentation != nil {
		return *x.Documentation
	}
	return ""
}

func (x *FlagInfo) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *FlagInfo) GetAbbreviation() string {
	if x != nil && x.Abbreviation != nil {
		return *x.Abbreviation
	}
	return ""
}

func (x *FlagInfo) GetAllowsMultiple() bool {
	if x != nil && x.AllowsMultiple != nil {
		return *x.AllowsMultiple
	}
	return Default_FlagInfo_AllowsMultiple
}

func (x *FlagInfo) GetEffectTags() []string {
	if x != nil {
		return x.EffectTags
	}
	return nil
}

func (x *FlagInfo) GetMetadataTags() []string {
	if x != nil {
		return x.MetadataTags
	}
	return nil
}

func (x *FlagInfo) GetDocumentationCategory() string {
	if x != nil && x.DocumentationCategory != nil {
		return *x.DocumentationCategory
	}
	return ""
}

func (x *FlagInfo) GetRequiresValue() bool {
	if x != nil && x.RequiresValue != nil {
		return *x.RequiresValue
	}
	return false
}

func (x *FlagInfo) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *FlagInfo) GetOldName() string {
	if x != nil && x.OldName != nil {
		return *x.OldName
	}
	return ""
}

func (x *FlagInfo) GetDeprecationWarning() string {
	if x != nil && x.DeprecationWarning != nil {
		return *x.DeprecationWarning
	}
	return ""
}

func (x *FlagInfo) GetOptionExpansions() []string {
	if x != nil {
		return x.OptionExpansions
	}
	return nil
}

func (x *FlagInfo) GetTypeConverter() string {
	if x != nil && x.TypeConverter != nil {
		return *x.TypeConverter
	}
	return ""
}

func (x *FlagInfo) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

type FlagCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlagInfos     []*FlagInfo            `protobuf:"bytes,1,rep,name=flag_infos,json=flagInfos" json:"flag_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagCollection) Reset() {
	*x = FlagCollection{}
	mi := &file_src_main_protobuf_bazel_flags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagCollection) ProtoMessage() {}

func (x *FlagCollection) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_bazel_flags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagCollection.ProtoReflect.Descriptor instead.
func (*FlagCollection) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_bazel_flags_proto_rawDescGZIP(), []int{1}
}

func (x *FlagCollection) GetFlagInfos() []*FlagInfo {
	if x != nil {
		return x.FlagInfos
	}
	return nil
}

var File_src_main_protobuf_bazel_flags_proto protoreflect.FileDescriptor

const file_src_main_protobuf_bazel_flags_proto_rawDesc = "" +
	"\n" +
	"#src/main/protobuf/bazel_flags.proto\x12\vbazel_flags\"\xf1\x04\n" +
	"\bFlagInfo\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x121\n" +
	"\x11has_negative_flag\x18\x02 \x01(\b:\x05falseR\x0fhasNegativeFlag\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12\x1a\n" +
	"\bcommands\x18\x04 \x03(\tR\bcommands\x12\"\n" +
	"\fabbreviation\x18\x05 \x01(\tR\fabbreviation\x12.\n" +
	"\x0fallows_multiple\x18\x06 \x01(\b:\x05falseR\x0eallowsMultiple\x12\x1f\n" +
	"\veffect_tags\x18\a \x03(\tR\n" +
	"effectTags\x12#\n" +
	"\rmetadata_tags\x18\b \x03(\tR\fmetadataTags\x125\n" +
	"\x16documentation_category\x18\t \x01(\tR\x15documentationCategory\x12%\n" +
	"\x0erequires_value\x18\n" +
	" \x01(\bR\rrequiresValue\x12#\n" +
	"\rdefault_value\x18\r \x01(\tR\fdefaultValue\x12\x19\n" +
	"\bold_name\x18\v \x01(\tR\aoldName\x12/\n" +
	"\x13deprecation_warning\x18\f \x01(\tR\x12deprecationWarning\x12+\n" +
	"\x11option_expansions\x18\x0e \x03(\tR\x10optionExpansions\x12%\n" +
	"\x0etype_converter\x18\x0f \x01(\tR\rtypeConverter\x12\x1f\n" +
	"\venum_values\x18\x10 \x03(\tR\n" +
	"enumValues\"F\n" +
	"\x0eFlagCollection\x124\n" +
	"\n" +
	"flag_infos\x18\x01 \x03(\v2\x15.bazel_flags.FlagInfoR\tflagInfosBG\n" +
	"4com.google.devtools.build.lib.runtime.commands.protoB\x0fBazelFlagsProto"

var (
	file_src_main_protobuf_bazel_flags_proto_rawDescOnce sync.Once
	file_src_main_protobuf_bazel_flags_proto_rawDescData []byte
)

func file_src_main_protobuf_bazel_flags_proto_rawDescGZIP() []byte {
	file_src_main_protobuf_bazel_flags_proto_rawDescOnce.Do(func() {
		file_src_main_protobuf_bazel_flags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_main_protobuf_bazel_flags_proto_rawDesc), len(file_src_main_protobuf_bazel_flags_proto_rawDesc)))
	})
	return file_src_main_protobuf_bazel_flags_proto_rawDescData
}

var file_src_main_protobuf_bazel_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_main_protobuf_bazel_flags_proto_goTypes = []any{
	(*FlagInfo)(nil),       // 0: bazel_flags.FlagInfo
	(*FlagCollection)(nil), // 1: bazel_flags.FlagCollection
}
var file_src_main_protobuf_bazel_flags_proto_depIdxs = []int32{
	0, // 0: bazel_flags.FlagCollection.flag_infos:type_name -> bazel_flags.FlagInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_main_protobuf_bazel_flags_proto_init() }
func file_src_main_protobuf_bazel_flags_proto_init() {
	if File_src_main_protobuf_bazel_flags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_main_protobuf_bazel_flags_proto_rawDesc), len(file_src_main_protobuf_bazel_flags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_main_protobuf_bazel_flags_proto_goTypes,
		DependencyIndexes: file_src_main_protobuf_bazel_flags_proto_depIdxs,
		MessageInfos:      file_src_main_protobuf_bazel_flags_proto_msgTypes,
	}.Build()
	File_src_main_protobuf_bazel_flags_proto = out.File
	file_src_main_protobuf_bazel_flags_proto_goTypes = nil
	file_src_main_protobuf_bazel_flags_proto_depIdxs = nil
}
